import { EventEmitter, QueryList } from '@angular/core';
import { CollectionView } from 'wijmo/wijmo';
import { FlexGrid, CellRangeEventArgs } from 'wijmo/wijmo.grid';
import { FlexGridFilter } from 'wijmo/wijmo.grid.filter';
import { Menu } from 'wijmo/wijmo.input';
import { SearchRequest } from './search-request';
import { GridColumn } from '../utils/grid-column';
import { MenuItem } from '../utils/menu-item';
import { CatalogItem } from '../entities';
export declare class CatalogListComponent {
    private _emptyFilter;
    private _catalogList;
    private _currentFilter;
    private _currentSortedColumn;
    private _currentSortOrder;
    private _pageSize;
    private _serverSice;
    currentItem: CatalogItem;
    catalogView: CollectionView;
    readonly pageCount: number;
    columns: QueryList<GridColumn>;
    filter: FlexGridFilter;
    grid: FlexGrid;
    contextMenu: Menu;
    enabled: boolean;
    catalogList: CatalogItem[];
    contextMenuItems: MenuItem[];
    pageIndex: number;
    pageSize: number;
    serverSide: boolean;
    totalRows: number;
    searchRequested: EventEmitter<SearchRequest>;
    contextMenuClick: EventEmitter<MenuItem>;
    currentItemChanged: EventEmitter<CatalogItem>;
    itemSelected: EventEmitter<CatalogItem>;
    contextMenuOpen: EventEmitter<CatalogItem>;
    private setFilterType();
    ngAfterViewInit(): void;
    initialized(sender: FlexGrid, args: any): void;
    moveFirst(): void;
    movePrevious(): void;
    moveNext(): void;
    moveLast(): void;
    filterChanged(e: any, args: any): void;
    sortChanged(sender: FlexGrid, args: CellRangeEventArgs): void;
    createSearchRequest(pageIndex: number): SearchRequest;
    menuItemClicked(menu: Menu, args: any): void;
}
