"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//Frameworks
const core_1 = require("@angular/core");
const router_1 = require("@angular/router");
const forms_1 = require("@angular/forms");
const common_1 = require("@angular/common");
//Azteca Kernel
const index_1 = require("../../index");
const index_2 = require("../../editors/index");
//Features
const servidorsmtp_service_1 = require("../services/servidorsmtp.service");
const servidorsmtp_1 = require("../models/servidorsmtp");
let ServidoresSMTPEditor = ServidoresSMTPEditor_1 = class ServidoresSMTPEditor extends index_2.CatalogEditor {
    //
    constructor(router, route, formBuilder, changeDetector, context, location, servidorSMTPService) {
        super(context, changeDetector);
        this.router = router;
        this.route = route;
        this.formBuilder = formBuilder;
        this.changeDetector = changeDetector;
        this.context = context;
        this.location = location;
        this.servidorSMTPService = servidorSMTPService;
        this.servidorsmtp = new servidorsmtp_1.ServidorSMTPInfo();
        this.metodosAutentificacion = [];
        this.catalogForm = formBuilder.group({
            'codigo': ['', forms_1.Validators.required],
            'nombre': ['', forms_1.Validators.required],
            'hostName': ['', forms_1.Validators.required],
            'port': [''],
            'userName': [''],
            'password': [''],
            'authMethod': ['']
        });
        this.metodosAutentificacion =
            [
                { "id": "N", "nombre": "Ninguna" },
                { "id": "P", "nombre": "Contraseña Normal" },
                { "id": "A", "nombre": "Avanzado" }
            ];
    }
    onConfigureCatalog(options) {
        this.autogeneratedCode = options.codigoAutogenerado;
    }
    onCreatingItem() {
    }
    onViewingItem(id) {
        this.context.app.showSpinner();
        this.servidorSMTPService.getDetailByID(id)
            .then(info => {
            this.context.app.hideSpinner();
            this.servidorsmtp = info;
            this.setReadonlyMode();
        })
            .catch(error => this.handleError(error));
    }
    onCloningItem(id) {
        this.context.app.showSpinner();
        //
        this.servidorSMTPService.clone(id)
            .then(info => {
            this.context.app.hideSpinner();
            this.servidorsmtp = info;
        })
            .catch(error => this.handleError(error));
    }
    onLoadingItem(id) {
        this.context.app.showSpinner();
        this.servidorSMTPService.getDetailByID(id)
            .then(info => {
            this.context.app.hideSpinner();
            this.servidorsmtp = info;
        })
            .catch(error => this.handleError(error));
    }
    onSavingItem(args) {
        this.context.app.showSpinner();
        this.servidorSMTPService.update(this.servidorsmtp)
            .then(info => {
            this.context.app.hideSpinner();
            this.servidorsmtp = info;
            if (args.closeEditor)
                this.location.back();
            else
                this.showAlert('La información ha sido actualizada con éxito', 'success');
        })
            .catch(error => this.handleError(error));
    }
};
ServidoresSMTPEditor = ServidoresSMTPEditor_1 = __decorate([
    core_1.Component({
        selector: 'general-servidoressmtp-editor',
        template: `
      <form [formGroup]="catalogForm">

          <azteca-catalog-editor #catalogEditor 
                                 [title]="'ServidorSMTP'"
                                 [info]="servidorsmtp"
                                 [valid]="catalogForm.valid"
                                 (configureCatalog)="onConfigureCatalog($event)"
                                 (creatingItem)="onCreatingItem()"
                                 (viewingItem)="onViewingItem($event)"
                                 (cloningItem)="onCloningItem($event)"
                                 (savingItem)="onSavingItem($event)"
                                 (loadingItem)="onLoadingItem($event)">

              <div class="row">
                  <div class="col-xs-10 col-md-10">
                      <azteca-form-field [label]="'Código:'">
                          <catalog-code formControlName="codigo" [(ngModel)]="servidorsmtp.code" [automatic]="autogeneratedCode"></catalog-code>
                      </azteca-form-field>

                      <azteca-form-field [label]="'Nombre:'">
                          <az-textbox formControlName="nombre" [(ngModel)]="servidorsmtp.nombre"></az-textbox>
                      </azteca-form-field>

                  </div>
              </div>

        
              <div class="row">
                  <div class="col-xs-10">
						
                          <div class="row">
                              <div class="col-xs-10 col-md-8">
                                  <azteca-form-field [label]="'Nombre del host:'">
                                      <az-textbox formControlName="hostName" [(ngModel)]="servidorsmtp.hostName"></az-textbox>
                                  </azteca-form-field>
                    
                                  <azteca-form-field [label]="'Puerto:'">
                                      <az-textbox formControlName="port" [(ngModel)]="servidorsmtp.port"></az-textbox>
                                  </azteca-form-field>

                                  <azteca-form-field [label]="'Nombre del Usuario:'">
                                      <az-textbox formControlName="userName" [(ngModel)]="servidorsmtp.userName"></az-textbox>
                                  </azteca-form-field>

                                  <azteca-form-field [label]="'Contraseña:'">
                                      <az-textbox formControlName="password" [(ngModel)]="servidorsmtp.password"></az-textbox>
                                  </azteca-form-field>

                                  <azteca-form-field [label]="'Metodo de autentificación:'">
                                      <az-combobox formControlName="authMethod" [(ngModel)]="servidorsmtp.authMethod" [items]="metodosAutentificacion" [displayMember]="'nombre'" [valueMember]="'id'"></az-combobox>
                                  </azteca-form-field>

                              </div>
                          </div>

                  </div>
              </div>
            

          </azteca-catalog-editor>
      </form>
    `,
        providers: [
            {
                provide: index_1.BaseComponent, useExisting: core_1.forwardRef(() => ServidoresSMTPEditor_1)
            },
            {
                provide: index_1.CatalogService, useExisting: servidorsmtp_service_1.ServidorSMTPService
            }
        ]
    }),
    __metadata("design:paramtypes", [router_1.Router, router_1.ActivatedRoute, forms_1.FormBuilder, core_1.ChangeDetectorRef,
        index_1.Context, common_1.Location, servidorsmtp_service_1.ServidorSMTPService])
], ServidoresSMTPEditor);
exports.ServidoresSMTPEditor = ServidoresSMTPEditor;
var ServidoresSMTPEditor_1;
