import { Context } from '../context';
import { FormGroup } from '@angular/forms';
import { CatalogEditorComponent } from './catalog-editor.component';
import { BaseComponent } from '../base-component';
import { PolicyInfo } from '../security/policy';
export declare abstract class CatalogEditor extends BaseComponent {
    protected context: Context;
    errorMessage: string;
    catalogForm: FormGroup;
    readonlyMode: boolean;
    autogeneratedCode: boolean;
    editor: CatalogEditorComponent;
    constructor(context: Context);
    showAlert(message: string, type: string): void;
    handleError(error: any): void;
    setReadonlyMode(): void;
    applyPolicy(policy: PolicyInfo): void;
}
