import { EventEmitter } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { FormGroup } from '@angular/forms';
import { EditorEventArgs } from './editor-event-args';
import { CatalogInfo, CatalogService } from '../entities';
import { CatalogOptions } from '../custom/custom-catalog';
import { Context } from '../context';
import { Alert } from '../utils/alert';
export declare class CatalogEditorComponent {
    private router;
    private route;
    private location;
    private context;
    private catalogService;
    identity: number;
    readonlyMode: boolean;
    alerts: Alert[];
    widthClass: string[];
    defaultOptions: CatalogOptions;
    info: CatalogInfo;
    title: string;
    catalogForm: FormGroup;
    enabled: boolean;
    configureCatalog: EventEmitter<CatalogOptions>;
    creatingItem: EventEmitter<void>;
    viewingItem: EventEmitter<number>;
    loadingItem: EventEmitter<number>;
    cloningItem: EventEmitter<number>;
    savingItem: EventEmitter<EditorEventArgs>;
    constructor(router: Router, route: ActivatedRoute, location: Location, context: Context, catalogService: CatalogService<CatalogInfo>);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    loadConfiguration(): void;
    showAlert(message: string, type: string): void;
    closeAlert(i: number): void;
    private saveHandler();
    private saveCloseHanlder();
    protected onSaveItem(closeEditor: boolean): void;
    closeEditor(): void;
    private handleError(error);
}
