"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//Frameworks
var core_1 = require("@angular/core");
var router_1 = require("@angular/router");
var forms_1 = require("@angular/forms");
var common_1 = require("@angular/common");
//
var wijmo_1 = require("wijmo/wijmo");
//Azteca Kernel
var index_1 = require("../index");
var index_2 = require("../controls/index");
var index_3 = require("../editors/index");
//Locales
var index_4 = require("./index");
var EmpresasEditor = EmpresasEditor_1 = (function (_super) {
    __extends(EmpresasEditor, _super);
    //        
    function EmpresasEditor(router, route, formBuilder, context, empresaService, sucursalService, location) {
        var _this = _super.call(this, context) || this;
        _this.router = router;
        _this.route = route;
        _this.context = context;
        _this.empresaService = empresaService;
        _this.sucursalService = sucursalService;
        _this.location = location;
        _this.empresa = new index_4.EmpresaInfo();
        _this.sucursales = [];
        _this.catalogForm = formBuilder.group({
            'codigo': ['', forms_1.Validators.required],
            'nombre': ['', forms_1.Validators.required],
            'calle': [''],
            'numExt': [''],
            'numInt': [''],
            'colonia': [''],
            'logo': [null, index_2.AztecaValiators.validFile],
            'poblacion': [0, index_2.AztecaValiators.selected]
        });
        return _this;
    }
    EmpresasEditor.prototype.onConfigureCatalog = function (options) {
        this.autogeneratedCode = options.codigoAutogenerado;
    };
    EmpresasEditor.prototype.onCreatingItem = function () {
    };
    EmpresasEditor.prototype.onViewingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.empresaService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.empresa = info;
            _this.setReadonlyMode();
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    EmpresasEditor.prototype.onCloningItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        //
        this.empresaService.clone(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.empresa = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    EmpresasEditor.prototype.onLoadingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.empresaService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.empresa = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    EmpresasEditor.prototype.onSavingItem = function (args) {
        var _this = this;
        this.context.app.showSpinner();
        this.empresaService.update(this.empresa)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.empresa = info;
            if (args.closeEditor)
                _this.location.back();
            else
                _this.showAlert('La información ha sido actualizada con éxito', 'success');
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    //Manejo de sucursales
    EmpresasEditor.prototype.selectSucursalesTab = function () {
        wijmo_1.Control.invalidateAll();
    };
    return EmpresasEditor;
}(index_3.CatalogEditor));
__decorate([
    core_1.ViewChild(index_4.SucursalesManager),
    __metadata("design:type", index_4.SucursalesManager)
], EmpresasEditor.prototype, "siteManager", void 0);
EmpresasEditor = EmpresasEditor_1 = __decorate([
    core_1.Component({
        moduleId: module.id,
        selector: 'azteca-empresas-editor',
        templateUrl: './empresas.editor.html',
        providers: [
            {
                provide: index_1.BaseComponent, useExisting: core_1.forwardRef(function () { return EmpresasEditor_1; })
            },
            {
                provide: index_1.CatalogService, useExisting: index_4.EmpresaService
            }
        ]
    }),
    __metadata("design:paramtypes", [router_1.Router, router_1.ActivatedRoute, forms_1.FormBuilder,
        index_1.Context, index_4.EmpresaService, index_4.SucursalService, common_1.Location])
], EmpresasEditor);
exports.EmpresasEditor = EmpresasEditor;
var EmpresasEditor_1;

//# sourceMappingURL=empresas.editor.js.map
