"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//Frameworks
var core_1 = require("@angular/core");
var router_1 = require("@angular/router");
var forms_1 = require("@angular/forms");
var common_1 = require("@angular/common");
//Azteca Kernel
var index_1 = require("../index");
var index_2 = require("../editors/index");
//Locales
var grupo_1 = require("./grupo");
var GruposEditor = GruposEditor_1 = (function (_super) {
    __extends(GruposEditor, _super);
    function GruposEditor(context, router, route, location, formBuilder, grupoService) {
        var _this = _super.call(this, context) || this;
        _this.context = context;
        _this.router = router;
        _this.route = route;
        _this.location = location;
        _this.grupoService = grupoService;
        _this.grupo = new grupo_1.GrupoInfo();
        _this.catalogForm = formBuilder.group({
            'codigo': ['', forms_1.Validators.required],
            'nombre': ['', forms_1.Validators.required]
        });
        return _this;
    }
    GruposEditor.prototype.onConfigureCatalog = function (options) {
        this.autogeneratedCode = options.codigoAutogenerado;
    };
    GruposEditor.prototype.onCreatingItem = function () {
    };
    GruposEditor.prototype.onViewingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.grupoService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.grupo = info;
            _this.setReadonlyMode();
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    GruposEditor.prototype.onCloningItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        //
        this.grupoService.clone(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.grupo = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    GruposEditor.prototype.onLoadingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.grupoService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.grupo = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    GruposEditor.prototype.onSavingItem = function (args) {
        var _this = this;
        this.context.app.showSpinner();
        this.grupoService.update(this.grupo)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.grupo = info;
            if (args.closeEditor)
                _this.location.back();
            else
                _this.showAlert('La información ha sido actualizada con éxito', 'success');
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    //Manejo de miembros
    GruposEditor.prototype.selectTab = function () {
    };
    return GruposEditor;
}(index_2.CatalogEditor));
GruposEditor = GruposEditor_1 = __decorate([
    core_1.Component({
        moduleId: module.id,
        selector: 'security-grupos-editor',
        templateUrl: './grupos.editor.html',
        providers: [
            {
                provide: index_1.BaseComponent, useExisting: core_1.forwardRef(function () { return GruposEditor_1; })
            },
            {
                provide: index_1.CatalogService, useExisting: grupo_1.GrupoService
            }
        ]
    }),
    __metadata("design:paramtypes", [index_1.Context, router_1.Router, router_1.ActivatedRoute, common_1.Location, forms_1.FormBuilder,
        grupo_1.GrupoService])
], GruposEditor);
exports.GruposEditor = GruposEditor;
var GruposEditor_1;

//# sourceMappingURL=grupos.editor.js.map
