"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var core_1 = require("@angular/core");
var router_1 = require("@angular/router");
var forms_1 = require("@angular/forms");
var common_1 = require("@angular/common");
//
var context_1 = require("../context");
var catalog_editor_1 = require("../editors/catalog-editor");
var base_component_1 = require("../base-component");
//
var entities_1 = require("../entities");
var sucursal_1 = require("./sucursal");
var empresa_1 = require("./empresa");
var SucursalesEditor = SucursalesEditor_1 = (function (_super) {
    __extends(SucursalesEditor, _super);
    function SucursalesEditor(context, router, route, location, formBuilder, sucursalService, empresaService) {
        var _this = _super.call(this, context) || this;
        _this.context = context;
        _this.router = router;
        _this.route = route;
        _this.location = location;
        _this.sucursalService = sucursalService;
        _this.empresaService = empresaService;
        _this.sucursal = new sucursal_1.SucursalInfo();
        _this.catalogForm = formBuilder.group({
            'codigo': ['', forms_1.Validators.required],
            'nombre': ['', forms_1.Validators.required],
            'nombreLargo': [''],
            'calle': [''],
            'numExt': [''],
            'numInt': [''],
            'colonia': [''],
            'cp': [''],
            'poblacion': [0],
            'telefono1': [''],
            'telefono2': [''],
            'fax': [''],
            'paginaWeb': [''],
            'correo': ['']
        });
        return _this;
    }
    SucursalesEditor.prototype.ngOnInit = function () {
        var _this = this;
        this.route.params.forEach(function (params) {
            _this.idEmpresa = +params['idEmpresa'];
        });
    };
    SucursalesEditor.prototype.onConfigureCatalog = function (options) {
        this.autogeneratedCode = options.codigoAutogenerado;
    };
    SucursalesEditor.prototype.onCreatingItem = function () {
        var _this = this;
        //Asignar y cargar datos de la empresa que dependerá la sucursal
        this.sucursal.idCompany = this.idEmpresa;
        this.empresaService.getDetailFromCache(this.idEmpresa)
            .then(function (empresa) { return _this.sucursal.empresa = empresa; })
            .catch(function (error) { return _this.handleError(error); });
    };
    SucursalesEditor.prototype.onViewingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.sucursalService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.sucursal = info;
            _this.setReadonlyMode();
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    SucursalesEditor.prototype.onCloningItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        //
        this.sucursalService.clone(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.sucursal = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    SucursalesEditor.prototype.onLoadingItem = function (id) {
        var _this = this;
        this.context.app.showSpinner();
        this.sucursalService.getDetailByID(id)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.sucursal = info;
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    SucursalesEditor.prototype.onSavingItem = function (args) {
        var _this = this;
        this.context.app.showSpinner();
        this.sucursalService.update(this.sucursal)
            .then(function (info) {
            _this.context.app.hideSpinner();
            _this.sucursal = info;
            if (args.closeEditor)
                _this.location.back();
            else
                _this.showAlert('La información ha sido actualizada con éxito', 'success');
        })
            .catch(function (error) { return _this.handleError(error); });
    };
    //Manejo de miembros
    SucursalesEditor.prototype.selectMiembrosTab = function () {
    };
    return SucursalesEditor;
}(catalog_editor_1.CatalogEditor));
SucursalesEditor = SucursalesEditor_1 = __decorate([
    core_1.Component({
        moduleId: module.id,
        selector: 'azteca-sucursales-editor',
        templateUrl: './sucursales.editor.html',
        providers: [
            {
                provide: base_component_1.BaseComponent, useExisting: core_1.forwardRef(function () { return SucursalesEditor_1; })
            },
            {
                provide: entities_1.CatalogService, useExisting: sucursal_1.SucursalService
            }
        ]
    }),
    __metadata("design:paramtypes", [context_1.Context, router_1.Router, router_1.ActivatedRoute, common_1.Location, forms_1.FormBuilder,
        sucursal_1.SucursalService, empresa_1.EmpresaService])
], SucursalesEditor);
exports.SucursalesEditor = SucursalesEditor;
var SucursalesEditor_1;

//# sourceMappingURL=sucursales.editor.js.map
