import { ChangeDetectorRef } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Context, BaseComponent } from '../../index';
import { CatalogEditorComponent } from '../components/catalog-editor.component';
import { PolicyInfo } from '../../security/models/policy';
import { IEditor } from './editor';
export declare abstract class CatalogEditor extends BaseComponent implements IEditor {
    protected context: Context;
    protected changeDetector: ChangeDetectorRef;
    errorMessage: string;
    catalogForm: FormGroup;
    readonlyMode: boolean;
    readonly dirty: boolean;
    readonly canceled: boolean;
    autogeneratedCode: boolean;
    editor: CatalogEditorComponent;
    constructor(context: Context, changeDetector: ChangeDetectorRef);
    ngOnInit(): void;
    showAlert(message: string, type: string): void;
    reset(): void;
    handleError(error: any): void;
    setReadonlyMode(): void;
    applyPolicy(policy: PolicyInfo): void;
}
