import { ChangeDetectorRef } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { TreeNode } from 'angular2-tree-component';
import { Context, HierarchyInfo, HierarchyNode } from '../../index';
import { HierarchyManagerComponent } from '../components/hierarchy-manager.component';
export declare class HierarchyManager {
    protected context: Context;
    protected changeDetector: ChangeDetectorRef;
    errorMessage: string;
    nodeForm: FormGroup;
    enabled: boolean;
    allowNew: boolean;
    allowEdit: boolean;
    allowDelete: boolean;
    allowCopy: boolean;
    autogeneratedCode: boolean;
    manager: HierarchyManagerComponent;
    constructor(context: Context, changeDetector: ChangeDetectorRef);
    ngOnInit(): void;
    showAlert(message: string, type: string): void;
    showEditor(): void;
    hideEditor(): void;
    addNode(info: HierarchyInfo<HierarchyNode>, parentNode: TreeNode): void;
    updateNode(info: HierarchyInfo<HierarchyNode>): void;
    deleteNode(node: TreeNode): void;
    reset(): void;
    handleError(error: any): void;
}
