import { EventEmitter, QueryList } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Menu } from 'wijmo/wijmo.input';
import { EditorEventArgs } from '../models/editor-event-args';
import { Context, CatalogInfo, CatalogService } from '../../index';
import { CatalogOptions } from '../../custom/models/catalog-options';
import { Alert, MenuItemDirective, MenuItem } from '../../controls/index';
export declare class CatalogEditorComponent {
    private router;
    private route;
    private location;
    private context;
    private catalogService;
    identity: number;
    readonlyMode: boolean;
    alerts: Alert[];
    widthClass: string[];
    defaultOptions: CatalogOptions;
    info: CatalogInfo;
    title: string;
    valid: boolean;
    enabled: boolean;
    configureCatalog: EventEmitter<CatalogOptions>;
    creatingItem: EventEmitter<void>;
    viewingItem: EventEmitter<number>;
    loadingItem: EventEmitter<number>;
    cloningItem: EventEmitter<number>;
    savingItem: EventEmitter<EditorEventArgs>;
    menuItemClick: EventEmitter<MenuItem>;
    menuItems: QueryList<MenuItemDirective>;
    constructor(router: Router, route: ActivatedRoute, location: Location, context: Context, catalogService: CatalogService<CatalogInfo>);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    loadConfiguration(): void;
    triggerOperation(): void;
    showAlert(message: string, type: string): void;
    closeAlert(i: number): void;
    private saveHandler();
    private saveCloseHanlder();
    protected onSaveItem(closeEditor: boolean): void;
    closeEditor(): void;
    onMenuItemClicked(menu: Menu, args: any): void;
    private handleError(error);
}
