import { EventEmitter, QueryList } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { ITreeOptions, IActionMapping, TreeNode } from 'angular2-tree-component';
import { ModalDirective } from 'ng2-bootstrap';
import { Menu } from 'wijmo/wijmo.input';
import { Context, CatalogInfo, CatalogService, HierarchyInfo, HierarchyNode } from '../../index';
import { CatalogOptions } from '../../custom/models/catalog-options';
import { Alert, MenuItem, MenuItemDirective, ToolbarButton } from '../../controls/index';
export declare class HierarchyManagerComponent {
    private context;
    private catalogService;
    private router;
    private route;
    private location;
    alerts: Alert[];
    defaultOptions: CatalogOptions;
    menuItems: MenuItem[];
    actionMapping: IActionMapping;
    treeOptions: ITreeOptions;
    customMenuItems: QueryList<MenuItemDirective>;
    editDialog: ModalDirective;
    nodes: HierarchyInfo<HierarchyNode>[];
    title: string;
    enabled: boolean;
    currentNode: TreeNode;
    configureCatalog: EventEmitter<CatalogOptions>;
    menuItemClick: EventEmitter<MenuItem>;
    currentNodeChanged: EventEmitter<TreeNode>;
    creatingNode: EventEmitter<TreeNode>;
    editingNode: EventEmitter<TreeNode>;
    savingNode: EventEmitter<any>;
    savingHierarchy: EventEmitter<HierarchyNode[]>;
    constructor(context: Context, catalogService: CatalogService<CatalogInfo>, router: Router, route: ActivatedRoute, location: Location);
    ngAfterViewInit(): void;
    loadConfiguration(): void;
    createMenu(): void;
    mainToolbarHandler(button: ToolbarButton): void;
    onMenuItemClick(menu: Menu, args: any): void;
    showEditor(): void;
    onCurrentNodeChanged(args: any): void;
    onMoveNode(args: any): void;
    onCommitEdit(): void;
    onCancelEdit(): void;
    private handleError(error);
}
